{% set name = "inetutils" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/inetutils/{{ name }}-{{ version }}.tar.gz
  sha256: fa043bbbc426eae1869070d2b6e29a98069615ac00681cdb92e20911d9292260
  patches:
    - fix-2_5_3b0f9a2.patch  # [osx]
    - fix-2_5_e158f9c.patch  # [osx]
    - fix-2_5_9a3da00.patch  # [osx]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - help2man
    - ncurses               # [build_platform != target_platform]
    - libxcrypt             # [build_platform != target_platform]
    - libidn2               # [build_platform != target_platform]
    - sed
  host:
    - ncurses
    - libxcrypt
    - libidn2

test:
  commands:
    - test -f $PREFIX/bin/telnet  # [unix]
    - telnet --version

about:
  home: https://www.gnu.org/software/inetutils/
  summary: 'Inetutils is a collection of common network programs'
  description: |
    Inetutils is a collection of common network programs. It includes:
      - An inetd meta-server.
      - An ftp client and server.
      - A telnet client and server.
      - An rsh client and server.
      - An rlogin client and server.
      - A tftp client and server.
      - A talk client and server.
      - A syslogd daemon.
      - Network tools: ping, ping6, traceroute, whois.
      - Admin tools: hostname, dnsdomainname, ifconfig
    And more...
    logger is not included in this distribution
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - danielnachun
    - chrros95
