{% set name = "inetutils" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/inetutils/{{ name }}-{{ version }}.tar.gz
  sha256: ccaa256e0d646df7f285ff158a3291f37cd1fc8382f3774d22f7254127635da7

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf
    - automake
    - m4
    - make
    - help2man
    - sed
    - ncurses               # [build_platform != target_platform]
    - libxcrypt             # [build_platform != target_platform]
    - libidn2               # [build_platform != target_platform]
  host:
    - ncurses
    - libxcrypt
    - libidn2

test:
  commands:
    - test -f $PREFIX/bin/telnet  # [unix]
    - telnet --version

about:
  home: https://www.gnu.org/software/inetutils/
  summary: 'Inetutils is a collection of common network programs'
  description: |
    Inetutils is a collection of common network programs. It includes:
      - An inetd meta-server.
      - An ftp client and server.
      - A telnet client and server.
      - An rsh client and server.
      - An rlogin client and server.
      - A tftp client and server.
      - A talk client and server.
      - A syslogd daemon.
      - Network tools: ping, ping6, traceroute, whois.
      - Admin tools: hostname, dnsdomainname, ifconfig
    And more...
    logger is not included in this distribution
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - danielnachun
    - chrros95
